name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
        git clone https://github.com/kerm-me/docdown.git
        pip install -r requirements.txt
        pip install playwright
        python3 -m playwright install
        playwright install
        python run.py 'https://max.book118.com/html/2017/1105/139064432.shtm'
        
